/**
 * Created by Administrator on 2016/7/3.
 */
$(document).ready(function(){
    var index=true;
    $(".nav2 li:first-child a").click(function(){
        if(index){
            $(this).addClass("icon-x");
            $(".nav3").css({
                height:"100%"
            });
            index=false;
        }else{
            $(this).removeClass("icon-x");
            $(".nav3").css({
                height:0
            });
            index=true;
        }
    });
    $("section:nth-of-type(2)").hover(function(){
        $(this).children(".left").css({"opacity":1});
        $(this).children(".right").css({"opacity":1});
    },function(){
        $(this).children(".left").css({"opacity":0});
        $(this).children(".right").css({"opacity":0});
    });
    /*$(".banner").animate({"left":"-100%"},1000);*/
    var step=0;
    $(".btn").children("span").eq(0).addClass("span");
    $(".left").click(function(){
        step+=1;
        if(step==4){
            step=0;
        }
        $(".banner").animate({"left":"-"+100*step+"%"},1000);
        $(".btn").children("span").eq(step).addClass("span");
        $(".btn").children("span").eq(step).siblings("span").removeClass("span");
    });
    $(".right").click(function(){
        step-=1;
        if(step==-1){
            step=3;
        }
        $(".banner").animate({"left":"-"+100*step+"%"},1000);
        $(".btn").children("span").eq(step).addClass("span");
        $(".btn").children("span").eq(step).hover(function(){
            $(this).css("background","#fff");
        },function(){
            $(this).css("background","#aaa");
        });
        $(".btn").children("span").eq(step).siblings("span").removeClass("span");
    });
    var footerIndex=true;
    $(".jia").each(function(i){
        $(this).click(function(){
           $(this).parent("h3").siblings("ul").slideToggle(300);
        });
    })
});